const express = require('express');
const app = express();

const musicNames = [
  'Shape of You', 
  'Bohemian Rhapsody', 
  'Billie Jean', 
  'Hey Jude', 
  'Sweet Child o\' Mine',
  'Stairway to Heaven',
  'Like a Rolling Stone',
  'Smells Like Teen Spirit',
  'What\'s Going On',
  'Imagine',
  'Hotel California',
  'I Want to Hold Your Hand',
  'Blowin\' in the Wind',
  'Yesterday',
  'Let It Be',
  'Purple Haze',
  'No Woman, No Cry',
  'Johnny B. Goode',
  'My Generation',
  'Dancing Queen',
  'Good Vibrations',
  'Hallelujah',
  'Every Breath You Take',
  'A Day in the Life',
  'Stand by Me',
  'Papa\'s Got a Brand New Bag',
  'Gimme Shelter',
  'What\'d I Say',
  'My Girl',
  'God Only Knows',
  'Im Just Ken - Ryan Gosling',
  'STAY - The Kid LAROI & Justin Bieber',
  'As It Was - Harry Styles',
  'WAIT FOR U (feat Drake & Tems) - Future',
  'Super Gremlin - Kodak Black',
  'Easy on Me - Adele',
  'Heat Waves - Glass Animals',
  'Cold Heart (PNAU Remix) - Elton John & Dua Lipa',
  'Hiss - Megan Thee Stallion',
  'Yes, And? - Ariana Grande',
  'Lovin on Me - Jack Harlow',
  'Rockin’ Around the Christmas Tree - Brenda Lee',
  'Bad Guy - Billie Eilish',
  'Old Town Road - Lil Nas X',
  'Senorita - Shawn Mendes, Camila Cabello',
  'Lose You to Love Me - Selena Gomez',
  'Dance Monkey - Tones and I',
  'Circles - Post Malone',
  'Memories - Maroon 5',
  '10,000 Hours - Dan + Shay, Justin Bieber',
  'Someone You Loved - Lewis Capaldi',
  'Roxanne - Arizona Zervas',
  'Yummy - Justin Bieber',
  'Blinding Lights - The Weeknd',
  'The Box - Roddy Ricch',
  'Dont Start Now ',
  'Life Is Good - Future ft. Drake',
  'Intentions - Justin Bieber ft. Quavo',
  'Say So - Doja Cat',
  'Adore You - Harry Styles',
  'Toosie Slide - Drake',
  'Blinding Lights - The Weeknd',
  'Savage Love - Jawsh 685, Jason Derulo',
  'Watermelon Sugar - Harry Styles',
  'Rockstar - DaBaby ft. Roddy Ricch',
  'Whats Poppin - Jack Harlow',
  'Cardigan - Taylor Swift',
  'WAP - Cardi B ft. Megan Thee Stallion',
  'Dynamite - BTS',
  'Mood - 24kGoldn ft. iann dior',
  'Positions Ariana Grande',
  'Therefore I Am Billie Eilish',
  'Levitating - Dua Lipa',
  'Peaches - Justin Bieber ft. Daniel Caesar, Giveon',
  'Leave The Door Open - Silk Sonic (Bruno Mars, Anderson .Paak)',
  'Save Your Tears - The Weeknd & Ariana Grande',
  'Kiss Me More - Doja Cat ft. SZA',
  'Montero (Call Me By Your Name) - Lil Nas X',
  'Astronaut In The Ocean - Masked Wolf',
  'Rapstar - Polo G',
  'Without You - The Kid LAROI',
  'Good 4 U - Olivia Rodrigo',
  'Deja Vu - Olivia Rodrigo',
  'Traitor - Olivia Rodrigo',
  'Drivers License - Olivia Rodrigo',
  'Best Friend - Saweetie ft. Doja Cat',
  'Heartbreak Anniversary - Giveon',
  'Beautiful Mistakes - Maroon 5 ft. Megan Thee Stallion',
  'Up - Cardi B',
  'Blame It On You - Jason Aldean',
  'Track Star - Mooski',
  'Forever After All - Luke Combs',
  'Heat Waves - Glass Animals',
  'Go Crazy - Chris Brown & Young Thug',
  'Made For You - Jake Owen',
  'Calling My Phone - Lil Tjay ft. 6LACK',
  'What’s Next - Drake',
  'Breaking Up Was Easy In The 90\'s - Sam Hunt',
  'Hell Of A View - Eric Church',
  'Nobody - Dylan Scott',
  'Glad You Exist - Dan + Shay',
  'Arcade - Duncan Laurence',
  'B-8EIGHT - K YO MAYA HO ',
  'APARIBHASIT | SWAR | ',
  
'TIMRO AANKHA - Swoopna Suman',
'AXIX - MERO PREM',
'Monkey Temple - Sangai Bachauna',
'Sujan Chapagain || LAJAYERA',
'Asare Mahinama',
'Uges Limbu ( Hamro Geet ) ',
'Mayale Bolayo Malai ',
'Mero Manaiko Phool Tipi ',
'Yabesh Thapa - Laakhau Hajarau',
'Suna Kancha ( सुन कान्छा ) - Trishna Gurung',
'Sajjan Raj Vaidya - Chitthi Bhitra',
'Basanta - Yedi Arko Janma Hunxa Bhane',
'Sadhai Sadhai Mantra ',
'NIHITA (निहित)',
'Putali | The Elements',
'Komal tyo timro - Sabin rai',
'BHANAI - Tribal Rain',
'"SAHARA" Tribal Rain sikkim ',
'KINA?-Waiba BuddhaMari',
'Ma Tira Farki Herana',
'Jau ki Basu By Sabin Rai',
'Timi Bhane | ALBATROSS',
'Yaad Ma Rakhnechhu',
'SAMARPAN - Sabin Rai & The Pharaoh',
'SAMJHANCHU - Sabin Rai & The Pharaoh',
'Mantramugdha',
'Hawa Jastai ',
'Timi Sangai - Apurva Tamang',
'Sajjan Raj Vaidya - Naganya Maya ',
'VEK - Eklai Jiuna Sikey',
'Waiba Buddha - Marijau',
'Fulai fulko bagaicha maa - Apurva Tamang ',
'Sajjan Raj Vaidya - Hataarindai',
'KO HAW TIMI | PRASHANT EZEKIEL RAI',
'Maaya [Timro Sabai Tyo Kura',
'ROCKHEADS | RANGA |',
'Mann Ka Bhawana - Apurva Tamang ',
'Nachahe ko Hoina ',
'Tu Na Jaane Aas Paas Hai Khuda',
'Channa Mereya',
'The Local Train - Aaoge Tum Kabhi ',
'Rishte Naate',
'Prateek Kuhad - Kasoor ',
'Tu Chahiye',
'Tere Hawaale ',
'LYRICAL : I love You ',
'Dil Diyan Gallan ',
'Saware ',
'O Saathi  ',
'Kun Faya Kun ',
'Ishq Sufiyana',
'O Re Piya ',
'Mere Bina',
'Heropanti: Tere Binaa ',
'Tu Jaane Na',
'Jab Saanson Me Teri Saansen Ghuli Toh',
'Main Rang Sharbaton Ka',
'Dhokha Dhadi ',
'Saiyyan - Kailash Kher',
'Meri khamoshi se baatein chun lena',
'Tera Naam Doon',
'Sukoon Mila',
'Asim Azhar - Jo Tu Na Mila',
'Humdard ',
'Arijit Singh: Meet ',
'Kyun meri aahaton se pardaKyun meri chahaton se parda',
'Atif Aslam: Pehli Dafa ',
'Pehli Nazar Mein Kaise Jaado Kar Diya',
'MEHERBANI | The Shaukeens ',
'Tera Chehra',
'LYRICAL: Pehla Pyaar',
'Aankhon Mein Teri Ajab Si ',
' Afreen Afreen',
'Itni Si Baat Hain',
'AAJ DIN CHADHEYA',
'Qaafirana',
'Main Rahoon Ya Na Rahoon',
'Tune Jo Na Kaha ',
'Mehrama - Love Aaj Kal ',
'DEKH LENA',
'Kaisi Teri Khudgarzi',
'khada hu aaj bhi wahi',
'Agar Tum Saath Ho',
'Hawayein Lyric Video',
'PHIR KABHI',
'King - Tu Aake Dekhle',
'"Maine Khud Ko Ragini MMS 2',
'Mann Jogiya ',
'Main Hoon Saath Tere',
'Mast Magan',
'Tere Naal',
'Malang Sajna',
'Kesariya - Brahmāstra ',
'Sabse Juda Hai Teri Adayein',
'Yeh Tune Kya Kiya ',
'Pehla Nasha Pehla khumar ',
'Bahara ',
'Kabhi Yaadon Mein ',
'Ed Sheeran - Thinking Out Loud',
'OneRepublic - Counting Stars',
'Major Lazer & DJ Snake - Lean On (feat. MØ) ',
'Alan Walker - Faded',
'Passenger | Let Her Go',
'Adele - Hello',
'Ed Sheeran - Perfect',
'Charlie Puth - We Dont Talk Anymore ',
'Clean Bandit - Rockabye',
'Calvin Harris, Rihanna - This Is What You Came For',
'Sia - Chandelier',
'Dua Lipa - New Rules',
'Ellie Goulding - Love Me Like You Do',
'twenty one pilots: Stressed Out',
'Eminem - Love The Way You Lie ft. Rihanna',
'Avicii - Wake Me Up',
'Shawn Mendes - Treat You Better',
'Bruno Mars - The Lazy Song',
'MAGIC! - Rude',
'The Chainsmokers & Coldplay - Something Just Like This ',
'John Legend - All of Me',
'Camila Cabello - Havana',
'Bruno Mars - That’s What I Like',
'Adele - Rolling in the Deep',
'Christina Perri - A Thousand Years ',
'Imagine Dragons - Believer ',
'Rihanna - Diamonds',
'Adele - Someone Like You',
'Jessie J - Bang Bang ft. Ariana Grande, Nicki Minaj',
'The Weeknd - The Hills',
'Sia - Cheap Thrills',
'Ellie Goulding - Burn',
'ZAYN - Dusk Till Dawn',
'Calvin Harris - Summer',
'One Direction - Drag Me Down'
];


let sentMusicNames = [];


function selectRandomMusicName() {
  if (sentMusicNames.length === musicNames.length) {
   
    sentMusicNames = [];
  }
  const availableMusicNames = musicNames.filter(name => !sentMusicNames.includes(name));
  const randomIndex = Math.floor(Math.random() * availableMusicNames.length);
  const selectedMusicName = availableMusicNames[randomIndex];
  sentMusicNames.push(selectedMusicName);
  return selectedMusicName;
}


function selectRandomMusicNameFromList() {
  return musicNames[Math.floor(Math.random() * musicNames.length)];
}


app.get('/kshitiz', (req, res) => {

  const randomMusicName = selectRandomMusicName();

 
  const correctOption = Math.random() < 0.5 ? 'A' : 'B';

  
  const decoyMusicName = selectRandomMusicNameFromList();

  
  const response = {
    music_name: randomMusicName,
    options: {
      [correctOption]: randomMusicName,
      [correctOption === 'A' ? 'B' : 'A']: decoyMusicName
    },
    correct_answer: correctOption
  };

  res.json(response);
});


const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});
